// Code generated by protoc-gen-go.
// source: paxos_msg.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	paxos_msg.proto

It has these top-level messages:
	PaxosNodeInfo
	SystemVariables
	AcceptorStateData
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PaxosNodeInfo struct {
	Rid              *uint64 `protobuf:"varint,1,req,name=Rid" json:"Rid,omitempty"`
	Nodeid           *uint64 `protobuf:"varint,2,req,name=Nodeid" json:"Nodeid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PaxosNodeInfo) Reset()                    { *m = PaxosNodeInfo{} }
func (m *PaxosNodeInfo) String() string            { return proto.CompactTextString(m) }
func (*PaxosNodeInfo) ProtoMessage()               {}
func (*PaxosNodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PaxosNodeInfo) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *PaxosNodeInfo) GetNodeid() uint64 {
	if m != nil && m.Nodeid != nil {
		return *m.Nodeid
	}
	return 0
}

type SystemVariables struct {
	Gid              *uint64          `protobuf:"varint,1,req,name=Gid" json:"Gid,omitempty"`
	MemberShip       []*PaxosNodeInfo `protobuf:"bytes,2,rep,name=MemberShip" json:"MemberShip,omitempty"`
	Version          *uint64          `protobuf:"varint,3,req,name=Version" json:"Version,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SystemVariables) Reset()                    { *m = SystemVariables{} }
func (m *SystemVariables) String() string            { return proto.CompactTextString(m) }
func (*SystemVariables) ProtoMessage()               {}
func (*SystemVariables) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SystemVariables) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *SystemVariables) GetMemberShip() []*PaxosNodeInfo {
	if m != nil {
		return m.MemberShip
	}
	return nil
}

func (m *SystemVariables) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type AcceptorStateData struct {
	InstanceID       *uint64 `protobuf:"varint,1,req,name=InstanceID" json:"InstanceID,omitempty"`
	PromiseID        *uint64 `protobuf:"varint,2,req,name=PromiseID" json:"PromiseID,omitempty"`
	PromiseNodeID    *uint64 `protobuf:"varint,3,req,name=PromiseNodeID" json:"PromiseNodeID,omitempty"`
	AcceptedID       *uint64 `protobuf:"varint,4,req,name=AcceptedID" json:"AcceptedID,omitempty"`
	AcceptedNodeID   *uint64 `protobuf:"varint,5,req,name=AcceptedNodeID" json:"AcceptedNodeID,omitempty"`
	AcceptedValue    []byte  `protobuf:"bytes,6,req,name=AcceptedValue" json:"AcceptedValue,omitempty"`
	Checksum         *uint32 `protobuf:"varint,7,req,name=Checksum" json:"Checksum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AcceptorStateData) Reset()                    { *m = AcceptorStateData{} }
func (m *AcceptorStateData) String() string            { return proto.CompactTextString(m) }
func (*AcceptorStateData) ProtoMessage()               {}
func (*AcceptorStateData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AcceptorStateData) GetInstanceID() uint64 {
	if m != nil && m.InstanceID != nil {
		return *m.InstanceID
	}
	return 0
}

func (m *AcceptorStateData) GetPromiseID() uint64 {
	if m != nil && m.PromiseID != nil {
		return *m.PromiseID
	}
	return 0
}

func (m *AcceptorStateData) GetPromiseNodeID() uint64 {
	if m != nil && m.PromiseNodeID != nil {
		return *m.PromiseNodeID
	}
	return 0
}

func (m *AcceptorStateData) GetAcceptedID() uint64 {
	if m != nil && m.AcceptedID != nil {
		return *m.AcceptedID
	}
	return 0
}

func (m *AcceptorStateData) GetAcceptedNodeID() uint64 {
	if m != nil && m.AcceptedNodeID != nil {
		return *m.AcceptedNodeID
	}
	return 0
}

func (m *AcceptorStateData) GetAcceptedValue() []byte {
	if m != nil {
		return m.AcceptedValue
	}
	return nil
}

func (m *AcceptorStateData) GetChecksum() uint32 {
	if m != nil && m.Checksum != nil {
		return *m.Checksum
	}
	return 0
}

func init() {
	proto.RegisterType((*PaxosNodeInfo)(nil), "common.PaxosNodeInfo")
	proto.RegisterType((*SystemVariables)(nil), "common.SystemVariables")
	proto.RegisterType((*AcceptorStateData)(nil), "common.AcceptorStateData")
}

func init() { proto.RegisterFile("paxos_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x69, 0x52, 0x53, 0xbd, 0x35, 0x8d, 0x1d, 0xa8, 0xcc, 0x32, 0x74, 0x15, 0x41, 0xb2,
	0xf0, 0x0d, 0xc4, 0x80, 0x64, 0xa1, 0x14, 0x03, 0x59, 0xb8, 0x91, 0x69, 0x72, 0xb5, 0x83, 0x9d,
	0xb9, 0x61, 0x66, 0x0a, 0xfa, 0x42, 0x3e, 0xa7, 0x4c, 0x7e, 0x04, 0x97, 0xf3, 0x9d, 0x33, 0xe7,
	0xbb, 0x90, 0x74, 0xe2, 0x8b, 0xec, 0x9b, 0xb2, 0x1f, 0x79, 0x67, 0xc8, 0x11, 0x8b, 0x1a, 0x52,
	0x8a, 0xf4, 0xf6, 0x16, 0xe2, 0x9d, 0x8f, 0x9e, 0xa9, 0xc5, 0x52, 0xbf, 0x13, 0x5b, 0x42, 0xf8,
	0x22, 0x5b, 0x3e, 0x4b, 0x83, 0x6c, 0xce, 0x56, 0x10, 0xf9, 0x40, 0xb6, 0x3c, 0xf0, 0xef, 0xed,
	0x2b, 0x24, 0xd5, 0xb7, 0x75, 0xa8, 0x6a, 0x61, 0xa4, 0xd8, 0x1f, 0xd1, 0xfa, 0xfe, 0xe3, 0x5f,
	0xff, 0x06, 0xe0, 0x09, 0xd5, 0x1e, 0x4d, 0x75, 0x90, 0x1d, 0x0f, 0xd2, 0x30, 0x5b, 0xde, 0x6d,
	0xf2, 0x41, 0x95, 0xff, 0xf7, 0x24, 0xb0, 0xa8, 0xd1, 0x58, 0x49, 0x9a, 0x87, 0xfd, 0xf6, 0xcf,
	0x0c, 0xd6, 0xf7, 0x4d, 0x83, 0x9d, 0x23, 0x53, 0x39, 0xe1, 0xb0, 0x10, 0x4e, 0x30, 0x06, 0x50,
	0x6a, 0xeb, 0x84, 0x6e, 0xb0, 0x2c, 0x46, 0xcb, 0x1a, 0x2e, 0x76, 0x86, 0x94, 0xb4, 0x1e, 0xf5,
	0x87, 0xb1, 0x0d, 0xc4, 0x23, 0xea, 0x05, 0xc5, 0xb0, 0xe9, 0x7f, 0x0f, 0x93, 0xd8, 0x96, 0x05,
	0x9f, 0xf7, 0xec, 0x1a, 0x56, 0x13, 0x1b, 0xbb, 0x67, 0xd3, 0xc4, 0xc4, 0x6b, 0x71, 0x3c, 0x21,
	0x8f, 0xd2, 0x20, 0xbb, 0x64, 0x57, 0x70, 0xfe, 0x70, 0xc0, 0xe6, 0xd3, 0x9e, 0x14, 0x5f, 0xa4,
	0x41, 0x16, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x68, 0x8b, 0x45, 0x4c, 0x01, 0x00, 0x00,
}
