// Code generated by protoc-gen-go.
// source: paxos_msg.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	paxos_msg.proto

It has these top-level messages:
	Header
	PaxosMsg
	CheckpointMsg
	PaxosNodeInfo
	SystemVariables
	AcceptorStateData
	MasterVariables
	PaxosValue
	BatchPaxosValues
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Cmdid            *int32 `protobuf:"varint,1,req,name=cmdid" json:"cmdid,omitempty"`
	Bodylen          *int32 `protobuf:"varint,2,req,name=bodylen" json:"bodylen,omitempty"`
	Version          *int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetCmdid() int32 {
	if m != nil && m.Cmdid != nil {
		return *m.Cmdid
	}
	return 0
}

func (m *Header) GetBodylen() int32 {
	if m != nil && m.Bodylen != nil {
		return *m.Bodylen
	}
	return 0
}

func (m *Header) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type PaxosMsg struct {
	MsgType             *int32  `protobuf:"varint,1,req,name=MsgType" json:"MsgType,omitempty"`
	InstanceID          *uint64 `protobuf:"varint,2,opt,name=InstanceID" json:"InstanceID,omitempty"`
	NodeID              *uint64 `protobuf:"varint,3,opt,name=NodeID" json:"NodeID,omitempty"`
	ProposalID          *uint64 `protobuf:"varint,4,opt,name=ProposalID" json:"ProposalID,omitempty"`
	ProposalNodeID      *uint64 `protobuf:"varint,5,opt,name=ProposalNodeID" json:"ProposalNodeID,omitempty"`
	Value               []byte  `protobuf:"bytes,6,opt,name=Value" json:"Value,omitempty"`
	PreAcceptID         *uint64 `protobuf:"varint,7,opt,name=PreAcceptID" json:"PreAcceptID,omitempty"`
	PreAcceptNodeID     *uint64 `protobuf:"varint,8,opt,name=PreAcceptNodeID" json:"PreAcceptNodeID,omitempty"`
	RejectByPromiseID   *uint64 `protobuf:"varint,9,opt,name=RejectByPromiseID" json:"RejectByPromiseID,omitempty"`
	NowInstanceID       *uint64 `protobuf:"varint,10,opt,name=NowInstanceID" json:"NowInstanceID,omitempty"`
	MinChosenInstanceID *uint64 `protobuf:"varint,11,opt,name=MinChosenInstanceID" json:"MinChosenInstanceID,omitempty"`
	LastChecksum        *uint32 `protobuf:"varint,12,opt,name=LastChecksum" json:"LastChecksum,omitempty"`
	Flag                *uint32 `protobuf:"varint,13,opt,name=Flag" json:"Flag,omitempty"`
	SystemVariables     []byte  `protobuf:"bytes,14,opt,name=SystemVariables" json:"SystemVariables,omitempty"`
	MasterVariables     []byte  `protobuf:"bytes,15,opt,name=MasterVariables" json:"MasterVariables,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *PaxosMsg) Reset()                    { *m = PaxosMsg{} }
func (m *PaxosMsg) String() string            { return proto.CompactTextString(m) }
func (*PaxosMsg) ProtoMessage()               {}
func (*PaxosMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PaxosMsg) GetMsgType() int32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *PaxosMsg) GetInstanceID() uint64 {
	if m != nil && m.InstanceID != nil {
		return *m.InstanceID
	}
	return 0
}

func (m *PaxosMsg) GetNodeID() uint64 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

func (m *PaxosMsg) GetProposalID() uint64 {
	if m != nil && m.ProposalID != nil {
		return *m.ProposalID
	}
	return 0
}

func (m *PaxosMsg) GetProposalNodeID() uint64 {
	if m != nil && m.ProposalNodeID != nil {
		return *m.ProposalNodeID
	}
	return 0
}

func (m *PaxosMsg) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PaxosMsg) GetPreAcceptID() uint64 {
	if m != nil && m.PreAcceptID != nil {
		return *m.PreAcceptID
	}
	return 0
}

func (m *PaxosMsg) GetPreAcceptNodeID() uint64 {
	if m != nil && m.PreAcceptNodeID != nil {
		return *m.PreAcceptNodeID
	}
	return 0
}

func (m *PaxosMsg) GetRejectByPromiseID() uint64 {
	if m != nil && m.RejectByPromiseID != nil {
		return *m.RejectByPromiseID
	}
	return 0
}

func (m *PaxosMsg) GetNowInstanceID() uint64 {
	if m != nil && m.NowInstanceID != nil {
		return *m.NowInstanceID
	}
	return 0
}

func (m *PaxosMsg) GetMinChosenInstanceID() uint64 {
	if m != nil && m.MinChosenInstanceID != nil {
		return *m.MinChosenInstanceID
	}
	return 0
}

func (m *PaxosMsg) GetLastChecksum() uint32 {
	if m != nil && m.LastChecksum != nil {
		return *m.LastChecksum
	}
	return 0
}

func (m *PaxosMsg) GetFlag() uint32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

func (m *PaxosMsg) GetSystemVariables() []byte {
	if m != nil {
		return m.SystemVariables
	}
	return nil
}

func (m *PaxosMsg) GetMasterVariables() []byte {
	if m != nil {
		return m.MasterVariables
	}
	return nil
}

type CheckpointMsg struct {
	MsgType              *int32  `protobuf:"varint,1,req,name=MsgType" json:"MsgType,omitempty"`
	NodeID               *uint64 `protobuf:"varint,2,req,name=NodeID" json:"NodeID,omitempty"`
	Flag                 *int32  `protobuf:"varint,3,opt,name=Flag" json:"Flag,omitempty"`
	UUID                 *uint64 `protobuf:"varint,4,req,name=UUID" json:"UUID,omitempty"`
	Sequence             *uint64 `protobuf:"varint,5,req,name=Sequence" json:"Sequence,omitempty"`
	CheckpointInstanceID *uint64 `protobuf:"varint,6,opt,name=CheckpointInstanceID" json:"CheckpointInstanceID,omitempty"`
	Checksum             *uint32 `protobuf:"varint,7,opt,name=Checksum" json:"Checksum,omitempty"`
	FilePath             *string `protobuf:"bytes,8,opt,name=FilePath" json:"FilePath,omitempty"`
	SMID                 *int32  `protobuf:"varint,9,opt,name=SMID" json:"SMID,omitempty"`
	Offset               *uint64 `protobuf:"varint,10,opt,name=Offset" json:"Offset,omitempty"`
	Buffer               []byte  `protobuf:"bytes,11,opt,name=Buffer" json:"Buffer,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (m *CheckpointMsg) Reset()                    { *m = CheckpointMsg{} }
func (m *CheckpointMsg) String() string            { return proto.CompactTextString(m) }
func (*CheckpointMsg) ProtoMessage()               {}
func (*CheckpointMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CheckpointMsg) GetMsgType() int32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *CheckpointMsg) GetNodeID() uint64 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

func (m *CheckpointMsg) GetFlag() int32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

func (m *CheckpointMsg) GetUUID() uint64 {
	if m != nil && m.UUID != nil {
		return *m.UUID
	}
	return 0
}

func (m *CheckpointMsg) GetSequence() uint64 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

func (m *CheckpointMsg) GetCheckpointInstanceID() uint64 {
	if m != nil && m.CheckpointInstanceID != nil {
		return *m.CheckpointInstanceID
	}
	return 0
}

func (m *CheckpointMsg) GetChecksum() uint32 {
	if m != nil && m.Checksum != nil {
		return *m.Checksum
	}
	return 0
}

func (m *CheckpointMsg) GetFilePath() string {
	if m != nil && m.FilePath != nil {
		return *m.FilePath
	}
	return ""
}

func (m *CheckpointMsg) GetSMID() int32 {
	if m != nil && m.SMID != nil {
		return *m.SMID
	}
	return 0
}

func (m *CheckpointMsg) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *CheckpointMsg) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type PaxosNodeInfo struct {
	Rid              *uint64 `protobuf:"varint,1,req,name=Rid" json:"Rid,omitempty"`
	Nodeid           *uint64 `protobuf:"varint,2,req,name=Nodeid" json:"Nodeid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PaxosNodeInfo) Reset()                    { *m = PaxosNodeInfo{} }
func (m *PaxosNodeInfo) String() string            { return proto.CompactTextString(m) }
func (*PaxosNodeInfo) ProtoMessage()               {}
func (*PaxosNodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PaxosNodeInfo) GetRid() uint64 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *PaxosNodeInfo) GetNodeid() uint64 {
	if m != nil && m.Nodeid != nil {
		return *m.Nodeid
	}
	return 0
}

type SystemVariables struct {
	Gid              *uint64          `protobuf:"varint,1,req,name=Gid" json:"Gid,omitempty"`
	MemberShip       []*PaxosNodeInfo `protobuf:"bytes,2,rep,name=MemberShip" json:"MemberShip,omitempty"`
	Version          *uint64          `protobuf:"varint,3,req,name=Version" json:"Version,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SystemVariables) Reset()                    { *m = SystemVariables{} }
func (m *SystemVariables) String() string            { return proto.CompactTextString(m) }
func (*SystemVariables) ProtoMessage()               {}
func (*SystemVariables) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SystemVariables) GetGid() uint64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *SystemVariables) GetMemberShip() []*PaxosNodeInfo {
	if m != nil {
		return m.MemberShip
	}
	return nil
}

func (m *SystemVariables) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type AcceptorStateData struct {
	InstanceID       *uint64 `protobuf:"varint,1,req,name=InstanceID" json:"InstanceID,omitempty"`
	PromiseID        *uint64 `protobuf:"varint,2,req,name=PromiseID" json:"PromiseID,omitempty"`
	PromiseNodeID    *uint64 `protobuf:"varint,3,req,name=PromiseNodeID" json:"PromiseNodeID,omitempty"`
	AcceptedID       *uint64 `protobuf:"varint,4,req,name=AcceptedID" json:"AcceptedID,omitempty"`
	AcceptedNodeID   *uint64 `protobuf:"varint,5,req,name=AcceptedNodeID" json:"AcceptedNodeID,omitempty"`
	AcceptedValue    []byte  `protobuf:"bytes,6,req,name=AcceptedValue" json:"AcceptedValue,omitempty"`
	Checksum         *uint32 `protobuf:"varint,7,req,name=Checksum" json:"Checksum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AcceptorStateData) Reset()                    { *m = AcceptorStateData{} }
func (m *AcceptorStateData) String() string            { return proto.CompactTextString(m) }
func (*AcceptorStateData) ProtoMessage()               {}
func (*AcceptorStateData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AcceptorStateData) GetInstanceID() uint64 {
	if m != nil && m.InstanceID != nil {
		return *m.InstanceID
	}
	return 0
}

func (m *AcceptorStateData) GetPromiseID() uint64 {
	if m != nil && m.PromiseID != nil {
		return *m.PromiseID
	}
	return 0
}

func (m *AcceptorStateData) GetPromiseNodeID() uint64 {
	if m != nil && m.PromiseNodeID != nil {
		return *m.PromiseNodeID
	}
	return 0
}

func (m *AcceptorStateData) GetAcceptedID() uint64 {
	if m != nil && m.AcceptedID != nil {
		return *m.AcceptedID
	}
	return 0
}

func (m *AcceptorStateData) GetAcceptedNodeID() uint64 {
	if m != nil && m.AcceptedNodeID != nil {
		return *m.AcceptedNodeID
	}
	return 0
}

func (m *AcceptorStateData) GetAcceptedValue() []byte {
	if m != nil {
		return m.AcceptedValue
	}
	return nil
}

func (m *AcceptorStateData) GetChecksum() uint32 {
	if m != nil && m.Checksum != nil {
		return *m.Checksum
	}
	return 0
}

type MasterVariables struct {
	MasterNodeid     *uint64 `protobuf:"varint,1,req,name=MasterNodeid" json:"MasterNodeid,omitempty"`
	Version          *uint64 `protobuf:"varint,2,req,name=Version" json:"Version,omitempty"`
	LeaseTime        *uint32 `protobuf:"varint,3,req,name=LeaseTime" json:"LeaseTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MasterVariables) Reset()                    { *m = MasterVariables{} }
func (m *MasterVariables) String() string            { return proto.CompactTextString(m) }
func (*MasterVariables) ProtoMessage()               {}
func (*MasterVariables) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MasterVariables) GetMasterNodeid() uint64 {
	if m != nil && m.MasterNodeid != nil {
		return *m.MasterNodeid
	}
	return 0
}

func (m *MasterVariables) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *MasterVariables) GetLeaseTime() uint32 {
	if m != nil && m.LeaseTime != nil {
		return *m.LeaseTime
	}
	return 0
}

type PaxosValue struct {
	SMID             *int32 `protobuf:"varint,1,req,name=SMID" json:"SMID,omitempty"`
	Value            []byte `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PaxosValue) Reset()                    { *m = PaxosValue{} }
func (m *PaxosValue) String() string            { return proto.CompactTextString(m) }
func (*PaxosValue) ProtoMessage()               {}
func (*PaxosValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PaxosValue) GetSMID() int32 {
	if m != nil && m.SMID != nil {
		return *m.SMID
	}
	return 0
}

func (m *PaxosValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type BatchPaxosValues struct {
	Values           []*PaxosValue `protobuf:"bytes,1,rep,name=Values" json:"Values,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *BatchPaxosValues) Reset()                    { *m = BatchPaxosValues{} }
func (m *BatchPaxosValues) String() string            { return proto.CompactTextString(m) }
func (*BatchPaxosValues) ProtoMessage()               {}
func (*BatchPaxosValues) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BatchPaxosValues) GetValues() []*PaxosValue {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "common.Header")
	proto.RegisterType((*PaxosMsg)(nil), "common.PaxosMsg")
	proto.RegisterType((*CheckpointMsg)(nil), "common.CheckpointMsg")
	proto.RegisterType((*PaxosNodeInfo)(nil), "common.PaxosNodeInfo")
	proto.RegisterType((*SystemVariables)(nil), "common.SystemVariables")
	proto.RegisterType((*AcceptorStateData)(nil), "common.AcceptorStateData")
	proto.RegisterType((*MasterVariables)(nil), "common.MasterVariables")
	proto.RegisterType((*PaxosValue)(nil), "common.PaxosValue")
	proto.RegisterType((*BatchPaxosValues)(nil), "common.BatchPaxosValues")
}

func init() { proto.RegisterFile("paxos_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0x9d, 0xc4, 0x49, 0x27, 0x76, 0x9c, 0xba, 0xff, 0xf6, 0xa7, 0x1f, 0x87, 0xc8, 0x27,
	0x57, 0x42, 0x3d, 0x70, 0x40, 0xe2, 0x48, 0x1b, 0x15, 0x22, 0x9a, 0x12, 0x35, 0x6d, 0x0f, 0x5c,
	0xd0, 0xd6, 0x9e, 0x24, 0x06, 0xdb, 0x6b, 0xbc, 0x1b, 0x20, 0x5f, 0x88, 0x6f, 0x03, 0x9f, 0x09,
	0xed, 0xf8, 0x4f, 0xd2, 0x96, 0x9b, 0xf7, 0xbd, 0xd9, 0x99, 0x37, 0x6f, 0x9f, 0xc1, 0xcd, 0xf9,
	0x4f, 0x21, 0x3f, 0xa7, 0x72, 0x79, 0x96, 0x17, 0x42, 0x09, 0xcf, 0x0a, 0x45, 0x9a, 0x8a, 0xcc,
	0x7f, 0x03, 0xd6, 0x7b, 0xe4, 0x11, 0x16, 0x9e, 0x03, 0x9d, 0x30, 0x8d, 0xe2, 0x88, 0x19, 0x23,
	0x33, 0xe8, 0x78, 0x2e, 0x74, 0x1f, 0x44, 0xb4, 0x49, 0x30, 0x63, 0x66, 0x0d, 0x7c, 0xc7, 0x42,
	0xc6, 0x22, 0x63, 0xad, 0x91, 0x11, 0x74, 0xfc, 0xdf, 0x26, 0xf4, 0x66, 0xba, 0xed, 0x54, 0x2e,
	0x35, 0x3b, 0x95, 0xcb, 0xdb, 0x4d, 0x8e, 0xd5, 0x7d, 0x0f, 0x60, 0x92, 0x49, 0xc5, 0xb3, 0x10,
	0x27, 0x63, 0x66, 0x8e, 0x8c, 0xa0, 0xed, 0x0d, 0xc0, 0xba, 0x16, 0x91, 0x3e, 0xb7, 0xe8, 0xec,
	0x01, 0xcc, 0x0a, 0x91, 0x0b, 0xc9, 0x93, 0xc9, 0x98, 0xb5, 0x09, 0x3b, 0x86, 0x41, 0x8d, 0x55,
	0xb5, 0x1d, 0xc2, 0x1d, 0xe8, 0xdc, 0xf3, 0x64, 0x8d, 0xcc, 0x1a, 0x19, 0x81, 0xed, 0x1d, 0x40,
	0x7f, 0x56, 0xe0, 0xdb, 0x30, 0xc4, 0x5c, 0x4d, 0xc6, 0xac, 0x4b, 0x35, 0x27, 0xe0, 0x36, 0x60,
	0x75, 0xb9, 0x47, 0xc4, 0x7f, 0xb0, 0x7f, 0x83, 0x5f, 0x30, 0x54, 0xe7, 0x9b, 0x59, 0x21, 0xd2,
	0x58, 0x6a, 0x6a, 0x8f, 0xa8, 0x23, 0x70, 0xae, 0xc5, 0x8f, 0x1d, 0xa9, 0x40, 0xf0, 0xff, 0x70,
	0x30, 0x8d, 0xb3, 0x8b, 0x95, 0x90, 0x98, 0xed, 0x90, 0x7d, 0x22, 0x0f, 0xc1, 0xbe, 0xe2, 0x52,
	0x5d, 0xac, 0x30, 0xfc, 0x2a, 0xd7, 0x29, 0xb3, 0x47, 0x46, 0xe0, 0x78, 0x36, 0xb4, 0x2f, 0x13,
	0xbe, 0x64, 0x0e, 0x9d, 0x4e, 0xc0, 0x9d, 0x6f, 0xa4, 0xc2, 0xf4, 0x9e, 0x17, 0x31, 0x7f, 0x48,
	0x50, 0xb2, 0x01, 0x29, 0x3f, 0x01, 0x77, 0xca, 0xa5, 0xc2, 0x62, 0x4b, 0xb8, 0x9a, 0xf0, 0xff,
	0x18, 0xe0, 0x50, 0xcb, 0x5c, 0xc4, 0x99, 0xfa, 0xa7, 0xa9, 0x5b, 0x03, 0xf5, 0x9b, 0xb4, 0x9b,
	0x91, 0xf4, 0x20, 0xfa, 0x74, 0x77, 0x47, 0x46, 0x6a, 0x6e, 0x08, 0xbd, 0x39, 0x7e, 0x5b, 0x63,
	0x16, 0x22, 0xeb, 0x10, 0xf2, 0x02, 0x0e, 0xb7, 0xfd, 0x77, 0x96, 0xb2, 0x68, 0xa9, 0x21, 0xf4,
	0x9a, 0x85, 0xba, 0xb4, 0xc2, 0x10, 0x7a, 0x97, 0x71, 0x82, 0x33, 0xae, 0x56, 0xe4, 0xe3, 0x9e,
	0x9e, 0x30, 0x9f, 0x56, 0xd6, 0x91, 0x9a, 0x8f, 0x8b, 0x85, 0x44, 0x55, 0x79, 0x36, 0x00, 0xeb,
	0x7c, 0xbd, 0x58, 0x60, 0x41, 0x36, 0xd9, 0xfe, 0x4b, 0x70, 0x28, 0x1f, 0x24, 0x39, 0x5b, 0x08,
	0xaf, 0x0f, 0xad, 0x9b, 0x2a, 0x60, 0x4d, 0x18, 0xe2, 0xa8, 0xdc, 0xc5, 0xff, 0xf4, 0xcc, 0x30,
	0x5d, 0xff, 0xae, 0xa9, 0x3f, 0x05, 0x98, 0x62, 0xfa, 0x80, 0xc5, 0x7c, 0x15, 0xe7, 0xcc, 0x1c,
	0xb5, 0x82, 0xfe, 0xab, 0xa3, 0xb3, 0x32, 0xc6, 0x67, 0x8f, 0xe7, 0xb8, 0xd0, 0xbd, 0x6f, 0xa2,
	0xaa, 0x7b, 0xff, 0x32, 0x60, 0xbf, 0x8c, 0x85, 0x28, 0xe6, 0x8a, 0x2b, 0x1c, 0x73, 0xc5, 0x9f,
	0x44, 0xb4, 0x9c, 0xb2, 0x0f, 0x7b, 0xdb, 0x84, 0x94, 0x26, 0x1f, 0x81, 0x53, 0x41, 0x4d, 0x78,
	0xcd, 0x32, 0xbc, 0x65, 0x4b, 0x8c, 0x1a, 0xcf, 0x8f, 0x61, 0x50, 0x63, 0x4d, 0x78, 0xab, 0x16,
	0x35, 0x5e, 0x87, 0xd8, 0x0c, 0xec, 0x27, 0x96, 0x9b, 0x81, 0xe3, 0x7f, 0x78, 0x16, 0x0e, 0x1d,
	0xb6, 0x12, 0xaa, 0xdc, 0x2a, 0x75, 0xee, 0xac, 0x68, 0xd6, 0xc2, 0xaf, 0x90, 0x4b, 0xbc, 0x8d,
	0x53, 0x24, 0x85, 0x8e, 0x7f, 0x0a, 0x40, 0xbe, 0xd0, 0xc8, 0xe6, 0xed, 0xca, 0x24, 0x35, 0xbf,
	0x93, 0xbe, 0x6d, 0xfb, 0xaf, 0x61, 0x78, 0xce, 0x55, 0xb8, 0xda, 0xd6, 0x4b, 0xcf, 0x07, 0xab,
	0xfc, 0x62, 0x06, 0x99, 0xed, 0x3d, 0x32, 0x9b, 0xa8, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67,
	0x64, 0x96, 0x0f, 0x58, 0x04, 0x00, 0x00,
}
